on:
  push:
    branches:
      - main
name: Deploy to ACI

jobs:
  frontend-job:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build ./app/back -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/notemon-frontend:${{ github.run_number }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/notemon-frontend:${{ github.run_number }}

      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: notemon-frontend
          ports: >
            80
            443
            8080
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/notemon-frontend:${{ github.run_number }}
          registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: notemon-frontend
          location: 'east us'